#!/bin/bash

ssh dev.core.wallpul.se "export CONSUMER_SECRET=$TWITTER_CONSUMER_SECRET CONSUMER_KEY=$TWITTER_CONSUMER_KEY ACCESS_TOKEN_SECRET=$TWITTER_ACCESS_TOKEN_SECRET ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN && bash -es" < ./deploy-remote.sh
